### ISSUE TITLE
wildweapons disables digging

### ISSUE THREAD

**Issue by TeTpaAka** [Kilarin/fractured#6]
Since wildweapons overwrites the default behaviour of tools with the fleshy damage group, every tool with this group becomes useless for digging. But in default, every(?) tool has the fleshy damage group, so you can't dig with a shovel any more.

**Comment by Kilarin** [comment]
YIKES!  That shouldn't happen!  That's why I made it call the original on_use.  Ick, didn't test properly at all.  ok, gotta fix or remove.  thanks.

**Comment by TeTpaAka** [comment]
https://github.com/Kilarin/fractured/commit/c181a552a3703d40ea55cb4b334d31f9fd0eceb1
